### ISSUE TITLE
Problem on localhost

### ISSUE THREAD

**Issue by melt-cdk** [fabianwennink/IconCaptcha-Plugin-jQuery-PHP#13]
Hello,
when i use on localhost (http://localhost/captcha/examples/regular-form.php), i have a problem with playload parameter. 
it works randomly.

![Capture d’écran 2022-09-26 à 14 26 24](https://user-images.githubusercontent.com/1032165/192278216-0b4bd55a-604e-4b20-8ffe-b696ae8f05c5.png)

Tx

**Comment by fabianwennink** [comment]
Hi [melt-cdk](https://github.com/melt-cdk)! I'm unable to reproduce the error you are reporting with the downloaded source and included examples. Did you make any modifications to the example code? If so, what steps did you take to produce the shown error?

**Comment by melt-cdk** [comment]
Hi @fabianwennink , no i use your example. tx

**Comment by glitcher32** [comment]
I am having this same exact issue using the examples. Sometimes the captcha loads, and most of the times it doesn't.

I click "VERIFY THAT YOU ARE HUMAN" and the blue circle shows forever and I get that same error in console that they did.

I'm using shared hosting not localhost though. (Apache)

**Comment by fabianwennink** [comment]
@dotworker This issue is related to https://github.com/fabianwennink/IconCaptcha-PHP/issues/26. Somehow, in very rare cases regardless of PHP version, rotating the image 180 degrees with `imagerotate` causes PHP to throw a 503. I've seen reports of this in other repositories as well, but there seems to not be a real answer or solution for it.

I'll see if I can implement some sort of workaround in a future version.
