### ISSUE TITLE
Demo IconCaptcha seemingly not loading

### ISSUE THREAD

**Issue by teddyfresco** [fabianwennink/IconCaptcha-Plugin-jQuery-PHP#26]
Hi, I've tried on
https://www.fabianwennink.nl/projects/IconCaptcha/#!demonstration
to activate the light and dark captcha, but on Chrome and Firefox last versions on Windows 10 it gets stuck on the pulsing circle (the one expanded below "Select the image displayed the least amount of times"), I don't see any image, is it normal?
Am I the only one?

**Comment by fabianwennink** [comment]
Hi @teddyfresco Thank you for the heads-up! I wasn't aware that the demo captchas are no longer working. After a quick check, it appears to be an issue with my hosting provider. I will discuss this issue with them.

**Comment by SpotAiR** [comment]
> Hi @teddyfresco Thank you for the heads-up! I wasn't aware that the demo captchas are no longer working. After a quick check, it appears to be an issue with my hosting provider. I will discuss this issue with them.
> 
> Edit: The demo captchas are now working again.

Hi,
Can you tell what is/was the issue with your hosting provider ?
It seems that I'm facing the same issue after installing IconCaptcha on my premise... and I can't find where is the problem. Maybe the same as yours ?
Thanks

**Comment by fabianwennink** [comment]
Hi @SpotAiR, the reason why the demo captchas were not working is because of seemingly an issue with the GD `imagerotate` function, which I only encounter on my hosting provider and not on my local dev environment (with either XAMPP or a Docker container). When using the [rotation option](https://github.com/fabianwennink/IconCaptcha-Plugin-jQuery-PHP/wiki/How-To-Use#php-1) in the captcha config, the image would often crash and return a 503 service unavailable error. I was unable to solve the issue, so I just disabled the rotation option for now.

If you open your browser's dev console and notice you get a 503 error, please disable the rotate option and see if it works. I have added this 'bug' to my todo list and will investigate it more at a later time. If you encounter a different error, or receive no error at all, it's unrelated to this issue.

**Comment by SpotAiR** [comment]
> Hi @SpotAiR, the reason why the demo captchas were not working is because of seemingly an issue with the GD `imagerotate` function, which I only encounter on my hosting provider and not on my local dev environment (with either XAMPP or a Docker container). When using the [rotation option](https://github.com/fabianwennink/IconCaptcha-Plugin-jQuery-PHP/wiki/How-To-Use#php-1) in the captcha config, the image would often crash and return a 503 service unavailable error. I was unable to solve the issue, so I just disabled the rotation option for now.
> 
> If you open your browser's dev console and notice you get a 503 error, please disable the rotate option and see if it works. I have added this 'bug' to my todo list and will investigate it more at a later time. If you encounter a different error, or receive no error at all, it's unrelated to this issue.

Thanks for your answer.
OK, not the same problem, disabled every image manipulation option, it's the same problem : when I click on "Verify that you are human", on the dev console : the captcha-request.php is called twice (1 POST then 1 GET, as on your demo), twice responding HTTP/200, but the response contains no image (the 2nd response is empty). No error log nowhere.
