### ISSUE TITLE
Wrong output for correct selection after wrong selection

### ISSUE THREAD

**Issue by AraByte** [fabianwennink/IconCaptcha-Plugin-jQuery-PHP#9]
After loading the captcha and choosing a wrong answer, the correct answer after that would throw a wrong output as well.
Check attached video

https://user-images.githubusercontent.com/94008527/142254052-a3a2a6ac-f3ce-4c25-99b1-dec2f3948bdc.mp4

**Comment by fabianwennink** [comment]
Hi, sorry for the late response. The issue shown in the video seems very odd, especially because it's on the demo page. It appears as if the back-end is refreshing the data properly when making an incorrect selection, but the image just stays the same. What should happen, is that with every wrong selection, a new image is generated. 

- Which browser and operating system are you using?
- Are you perhaps using some browser extension or anything else which might enfore aggresive image/assets caching? 
- Does this happen every time, or was this a single occurrence?

**Comment by Cage31** [comment]
Hi,
i have the same problem. This happen every time on firefox. There is no extension
First time the image is correctly displayed... then the new image is not displayed. Cache problem..

<img width="732" alt="captcha-cache" src="https://user-images.githubusercontent.com/2852664/149358645-e179d7f4-1f40-4eab-ae29-10676e075439.png">

**Comment by fabianwennink** [comment]
@Cage31 Thank you for the additional information. I just tried the demo myself with Firefox and it indeed shows the behaviour as described in this issue. I will implement a fix as soon as possible.

**Comment by fabianwennink** [comment]
This issue has been resolved in the latest release (version 3.0.1).
